//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeGrow.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModulesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModulesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeGrow.Controllers.ModulesResource", typeof(ModulesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100x100 стандартний фірмовий БОКС для встановлення модулів..
        /// </summary>
        internal static string _100x100_default_firmware_box_for_growing_and_modules_installation {
            get {
                return ResourceManager.GetString("100x100 default firmware box for growing and modules installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5MPx дивовижна камера у твій БОКС :) Найкращі таймлапси!.
        /// </summary>
        internal static string _5MPx_coolest_optical_cam_module_for_your_box___ {
            get {
                return ResourceManager.GetString("5MPx coolest optical cam module for your box :)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль камери.
        /// </summary>
        internal static string Camera_module {
            get {
                return ResourceManager.GetString("Camera module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вуглевий фільтр.
        /// </summary>
        internal static string Coal_filter {
            get {
                return ResourceManager.GetString("Coal filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маленький вуглевий фільтр для абсорбування повітря боксу.
        /// </summary>
        internal static string Coal_filter_that_is_used_to_absorb_smell_from_your_box_ {
            get {
                return ResourceManager.GetString("Coal filter that is used to absorb smell from your box.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірка рівня кислотності грунту.
        /// </summary>
        internal static string Gives_information_about_soil_pH_parameter {
            get {
                return ResourceManager.GetString("Gives information about soil pH parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Надає можливість отримувати точні дані температури у будь якій частині БОКСУ..
        /// </summary>
        internal static string Gives_precise_temperature_info {
            get {
                return ResourceManager.GetString("Gives precise temperature info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На відміну від звичайного модуля поливу, має антикорозійне покриття. Гарно підходить для звичайного грунту..
        /// </summary>
        internal static string Has_additional_defense_layer__Good_for_common_soil_ {
            get {
                return ResourceManager.GetString("Has additional defense layer. Good for common soil.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED Лампа 60x60.
        /// </summary>
        internal static string LED_Lamp_60x60 {
            get {
                return ResourceManager.GetString("LED Lamp 60x60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль виміру pH.
        /// </summary>
        internal static string pH_meter_module {
            get {
                return ResourceManager.GetString("pH meter module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Антикорозійний модуль поливу.
        /// </summary>
        internal static string Resist_soil_watering_module {
            get {
                return ResourceManager.GetString("Resist soil watering module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB, 100Wt LED.
        /// </summary>
        internal static string RGB__100Wt_LED {
            get {
                return ResourceManager.GetString("RGB, 100Wt LED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модуль поливу грунту.
        /// </summary>
        internal static string Soil_watering_module {
            get {
                return ResourceManager.GetString("Soil watering module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартний БОКС.
        /// </summary>
        internal static string Standart_box {
            get {
                return ResourceManager.GetString("Standart box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Термопара.
        /// </summary>
        internal static string Thermocouple {
            get {
                return ResourceManager.GetString("Thermocouple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цей модуль перевіряє вологість грунту. Гарно підходить для коко грунту..
        /// </summary>
        internal static string This_module_is_used_to_check_soil_humidity__Good_for_coco_soil_ {
            get {
                return ResourceManager.GetString("This module is used to check soil humidity. Good for coco soil.", resourceCulture);
            }
        }
    }
}
